included:
  - Cancel-It

excluded:
  - Cancel-It/Resources/Generated

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - unused_import
  - void_return

file_length:
  warning: 500
  error: 750
  ignore_comment_only_lines: true

line_length:
  warning: 150
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 50

type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 50
    error: 50
  validates_start_with_lowercase: true
